#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <command-to-run-on-alert>"
    exit 1
fi

alert_command="$1"

query_result=$(curl http://localhost:8090/alerts/thresholds)

alerts_length=$(echo $query_result | jq '.result | length')

alerts=$(echo $query_result | jq '.result')

if [ "$alerts_length" -gt 0 ]; then
    echo $alerts | $alert_command
fi
