-- Generated by generate.py — do not edit directly.

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.raw_mv TO flows.raw AS
    WITH temp AS (
        SELECT
            type,
            NumToFlowTypeString(type) AS type_str,

            sequence_num,
            sampling_rate,

            BytesToIPString(fks.sampler_address) AS sampler_address_str,
            BytesToIPNum(fks.sampler_address) AS sampler_address,

            toDateTime64(time_received_ns/1000000000, 9) AS time_received,
            toDateTime64(time_flow_start_ns/1000000000, 9) AS time_flow_start,
            toDateTime64(time_flow_end_ns/1000000000, 9) AS time_flow_end,

            bytes,
            bytes * if(sampling_rate = 0, flows.routers.default_sampling, sampling_rate) AS total_bytes,

            packets,
            packets * if(sampling_rate = 0, flows.routers.default_sampling, sampling_rate) AS total_packets,

            BytesToIPString(fks.src_addr) AS src_addr_str,
            BytesToIPNum(fks.src_addr) AS src_addr,

            BytesToIPString(fks.dst_addr) AS dst_addr_str,
            BytesToIPNum(fks.dst_addr) AS dst_addr,

            etype,
            NumToETypeString(etype) AS etype_str,

            proto,
            NumToProtoString(proto) AS proto_str,

            ip_tos,
            ip_ttl,
            ip_flags,

            tcp_flags,
            NumToTcpFlagsString(tcp_flags) AS tcp_flags_str,

            icmp_type,
            icmp_code,

            src_port,
            dst_port,

            src_as,
            dst_as,

            src_net,
            dst_net,

            BytesToIPNum(next_hop) AS next_hop,

            next_hop_as,

            BytesToIPNum(bgp_next_hop) AS bgp_next_hop,

            in_if,
            out_if,

            src_mac,
            dst_mac,

            forwarding_status,
            -- Fix for Juniper devices with `report-zero-oif-gw-on-discard` enabled:
            NumToForwardingStatusString(if(empty(fks.next_hop) = 1 AND out_if = 0, 2, forwarding_status)) AS forwarding_status_str,

            observation_domain_id,
            observation_point_id
        FROM flows.kafka_sink fks
        LEFT ANY JOIN flows.routers ON sampler_address_str == flows.routers.router_ip
    ),
    ip_list AS (
        SELECT DISTINCT dst_addr FROM temp
    ),
    dst_addr_to_prefixes AS (
        SELECT
            dst_addr,
            groupArray(p.prefix) AS prefixes
        FROM ip_list l, flows.prefixes_range p
        WHERE dst_addr BETWEEN p.start AND p.end
        GROUP BY dst_addr
    )
    SELECT
        temp.*,
        prefixes
    FROM temp
    LEFT JOIN dst_addr_to_prefixes USING dst_addr;

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_range_mv
REFRESH EVERY 1 MINUTE TO flows.prefixes_range AS
    WITH split_prefix AS (
        SELECT DISTINCT
            arrayJoin(prefixes) AS prefix,
            splitByChar('/', prefix) AS ip_mask,
            ip_mask[1] AS ip,
            toUInt8(ip_mask[2]) AS mask
        FROM flows.rules
    ),
    ipv4_prefixes AS (
        SELECT
            prefix,
            IPv4CIDRToRange(IPv4StringToNum(ip), mask) AS ip_range
        FROM split_prefix
        WHERE position(ip, '.') <> 0
    ),
    ipv6_prefixes AS (
        SELECT
            prefix,
            IPv6CIDRToRange(IPv6StringToNum(ip), mask) AS ip_range
        FROM split_prefix
        WHERE position(ip, '.') = 0
    )
    SELECT prefix, toUInt128(ip_range.1) AS start, toUInt128(ip_range.2) AS end FROM ipv4_prefixes
    UNION ALL
    SELECT prefix, toUInt128(ip_range.1) AS start, toUInt128(ip_range.2) AS end FROM ipv6_prefixes
    ORDER BY start, end;

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_src_1h_mv TO flows.prefixes_src_1h AS
SELECT 
    arrayJoin(prefixes) AS prefix, 
    multiIf(etype = 2048, IPv4NumToString(IPv4CIDRToRange(toIPv4(src_addr_str), 16).1), etype = 34525, IPv6NumToString(IPv6CIDRToRange(toIPv6(src_addr_str), 32).1), NULL) AS network, 
    toStartOfHour(time_received) AS time_received, 
    sum(total_bytes) AS bytes, 
    sum(total_packets) AS packets, 
    count() AS flows
FROM flows.raw 
WHERE isNotNull(network)
GROUP BY 
    prefix, 
    network, 
    time_received;

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_src_1d_mv
REFRESH EVERY 1 DAY APPEND TO flows.prefixes_src_1d AS
    SELECT
        prefix,
        network,
        toStartOfDay(time_received) AS time_received,
        sum(bytes) AS bytes,
        sum(packets) AS packets,
        sum(flows) AS flows
    FROM flows.prefixes_src_1h
    WHERE time_received >= NOW() - INTERVAL 1 DAY
    GROUP BY prefix, network, time_received;

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_ip_port_1m_mv TO flows.prefixes_ip_port_1m AS
    WITH precomputed AS (
        SELECT
            arrayJoin(prefixes) AS prefix,
            dst_addr_str AS dst_addr,
            dst_port,
            toStartOfMinute(time_received) AS time_received,
            total_bytes,
            total_packets,
            proto = 6 AS is_tcp,
            proto = 17 AS is_udp,
            proto = 47 AS is_gre,
            proto = 50 AS is_esp,
            (etype = 0x0800 AND proto = 1) OR (etype = 0x86dd AND proto = 58) AS is_icmp,
            is_tcp AND bitAnd(tcp_flags, 0x01) AS is_tcp_fin,
            is_tcp AND bitAnd(tcp_flags, 0x02) AS is_tcp_syn,
            is_tcp AND bitAnd(tcp_flags, 0x04) AS is_tcp_rst,
            is_tcp AND bitAnd(tcp_flags, 0x08) AS is_tcp_psh,
            is_tcp AND bitAnd(tcp_flags, 0x10) AS is_tcp_ack,
            is_tcp AND bitAnd(tcp_flags, 0x20) AS is_tcp_urg
        FROM flows.raw
    )
    SELECT
        prefix,
        dst_addr,
        dst_port,
        time_received,
        sum(total_bytes) AS any_bytes,
        sum(total_packets) AS any_packets,
        count() AS any_flows,
        sumIf(total_bytes, is_tcp) AS tcp_bytes,
        sumIf(total_packets, is_tcp) AS tcp_packets,
        countIf(is_tcp) AS tcp_flows,
        sumIf(total_bytes, is_udp) AS udp_bytes,
        sumIf(total_packets, is_udp) AS udp_packets,
        countIf(is_udp) AS udp_flows,
        sumIf(total_bytes, is_gre) AS gre_bytes,
        sumIf(total_packets, is_gre) AS gre_packets,
        countIf(is_gre) AS gre_flows,
        sumIf(total_bytes, is_esp) AS esp_bytes,
        sumIf(total_packets, is_esp) AS esp_packets,
        countIf(is_esp) AS esp_flows,
        sumIf(total_bytes, is_icmp) AS icmp_bytes,
        sumIf(total_packets, is_icmp) AS icmp_packets,
        countIf(is_icmp) AS icmp_flows,
        sumIf(total_bytes, is_tcp_fin) AS tcp_fin_bytes,
        sumIf(total_packets, is_tcp_fin) AS tcp_fin_packets,
        countIf(is_tcp_fin) AS tcp_fin_flows,
        sumIf(total_bytes, is_tcp_syn) AS tcp_syn_bytes,
        sumIf(total_packets, is_tcp_syn) AS tcp_syn_packets,
        countIf(is_tcp_syn) AS tcp_syn_flows,
        sumIf(total_bytes, is_tcp_rst) AS tcp_rst_bytes,
        sumIf(total_packets, is_tcp_rst) AS tcp_rst_packets,
        countIf(is_tcp_rst) AS tcp_rst_flows,
        sumIf(total_bytes, is_tcp_psh) AS tcp_psh_bytes,
        sumIf(total_packets, is_tcp_psh) AS tcp_psh_packets,
        countIf(is_tcp_psh) AS tcp_psh_flows,
        sumIf(total_bytes, is_tcp_ack) AS tcp_ack_bytes,
        sumIf(total_packets, is_tcp_ack) AS tcp_ack_packets,
        countIf(is_tcp_ack) AS tcp_ack_flows,
        sumIf(total_bytes, is_tcp_urg) AS tcp_urg_bytes,
        sumIf(total_packets, is_tcp_urg) AS tcp_urg_packets,
        countIf(is_tcp_urg) AS tcp_urg_flows
    FROM precomputed
    GROUP BY prefix, dst_addr, dst_port, time_received;

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_ip_1m_mv TO flows.prefixes_ip_1m AS
SELECT 
    prefix, 
    dst_addr, 
    time_received, 
    sum(any_bytes) AS any_bytes, 
    sum(any_packets) AS any_packets, 
    sum(any_flows) AS any_flows, 
    sum(tcp_bytes) AS tcp_bytes, 
    sum(tcp_packets) AS tcp_packets, 
    sum(tcp_flows) AS tcp_flows, 
    sum(udp_bytes) AS udp_bytes, 
    sum(udp_packets) AS udp_packets, 
    sum(udp_flows) AS udp_flows, 
    sum(gre_bytes) AS gre_bytes, 
    sum(gre_packets) AS gre_packets, 
    sum(gre_flows) AS gre_flows, 
    sum(esp_bytes) AS esp_bytes, 
    sum(esp_packets) AS esp_packets, 
    sum(esp_flows) AS esp_flows, 
    sum(icmp_bytes) AS icmp_bytes, 
    sum(icmp_packets) AS icmp_packets, 
    sum(icmp_flows) AS icmp_flows, 
    sum(tcp_fin_bytes) AS tcp_fin_bytes, 
    sum(tcp_fin_packets) AS tcp_fin_packets, 
    sum(tcp_fin_flows) AS tcp_fin_flows, 
    sum(tcp_syn_bytes) AS tcp_syn_bytes, 
    sum(tcp_syn_packets) AS tcp_syn_packets, 
    sum(tcp_syn_flows) AS tcp_syn_flows, 
    sum(tcp_rst_bytes) AS tcp_rst_bytes, 
    sum(tcp_rst_packets) AS tcp_rst_packets, 
    sum(tcp_rst_flows) AS tcp_rst_flows, 
    sum(tcp_psh_bytes) AS tcp_psh_bytes, 
    sum(tcp_psh_packets) AS tcp_psh_packets, 
    sum(tcp_psh_flows) AS tcp_psh_flows, 
    sum(tcp_ack_bytes) AS tcp_ack_bytes, 
    sum(tcp_ack_packets) AS tcp_ack_packets, 
    sum(tcp_ack_flows) AS tcp_ack_flows, 
    sum(tcp_urg_bytes) AS tcp_urg_bytes, 
    sum(tcp_urg_packets) AS tcp_urg_packets, 
    sum(tcp_urg_flows) AS tcp_urg_flows
FROM flows.prefixes_ip_port_1m 
GROUP BY 
    prefix, 
    dst_addr, 
    time_received;

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_proto_1m_mv TO flows.prefixes_proto_1m AS
SELECT 
    prefix, 
    time_received, 
    sum(any_bytes) AS any_bytes, 
    sum(any_packets) AS any_packets, 
    sum(any_flows) AS any_flows, 
    sum(tcp_bytes) AS tcp_bytes, 
    sum(tcp_packets) AS tcp_packets, 
    sum(tcp_flows) AS tcp_flows, 
    sum(udp_bytes) AS udp_bytes, 
    sum(udp_packets) AS udp_packets, 
    sum(udp_flows) AS udp_flows, 
    sum(gre_bytes) AS gre_bytes, 
    sum(gre_packets) AS gre_packets, 
    sum(gre_flows) AS gre_flows, 
    sum(esp_bytes) AS esp_bytes, 
    sum(esp_packets) AS esp_packets, 
    sum(esp_flows) AS esp_flows, 
    sum(icmp_bytes) AS icmp_bytes, 
    sum(icmp_packets) AS icmp_packets, 
    sum(icmp_flows) AS icmp_flows, 
    sum(tcp_fin_bytes) AS tcp_fin_bytes, 
    sum(tcp_fin_packets) AS tcp_fin_packets, 
    sum(tcp_fin_flows) AS tcp_fin_flows, 
    sum(tcp_syn_bytes) AS tcp_syn_bytes, 
    sum(tcp_syn_packets) AS tcp_syn_packets, 
    sum(tcp_syn_flows) AS tcp_syn_flows, 
    sum(tcp_rst_bytes) AS tcp_rst_bytes, 
    sum(tcp_rst_packets) AS tcp_rst_packets, 
    sum(tcp_rst_flows) AS tcp_rst_flows, 
    sum(tcp_psh_bytes) AS tcp_psh_bytes, 
    sum(tcp_psh_packets) AS tcp_psh_packets, 
    sum(tcp_psh_flows) AS tcp_psh_flows, 
    sum(tcp_ack_bytes) AS tcp_ack_bytes, 
    sum(tcp_ack_packets) AS tcp_ack_packets, 
    sum(tcp_ack_flows) AS tcp_ack_flows, 
    sum(tcp_urg_bytes) AS tcp_urg_bytes, 
    sum(tcp_urg_packets) AS tcp_urg_packets, 
    sum(tcp_urg_flows) AS tcp_urg_flows
FROM flows.prefixes_ip_1m 
GROUP BY 
    prefix, 
    time_received;

-- 1h rollups: p95/max of per-minute values (from 1m tables)

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_ip_port_1h_mv
REFRESH EVERY 1 HOUR APPEND TO flows.prefixes_ip_port_1h AS
    WITH stats AS (
        SELECT
            prefix,
            dst_addr,
            dst_port,
            toStartOfHour(time_received) AS time_received,
        sum(any_bytes) AS any_bytes,
        sum(any_packets) AS any_packets,
        sum(any_flows) AS any_flows,
        sum(tcp_bytes) AS tcp_bytes,
        sum(tcp_packets) AS tcp_packets,
        sum(tcp_flows) AS tcp_flows,
        sum(udp_bytes) AS udp_bytes,
        sum(udp_packets) AS udp_packets,
        sum(udp_flows) AS udp_flows,
        sum(gre_bytes) AS gre_bytes,
        sum(gre_packets) AS gre_packets,
        sum(gre_flows) AS gre_flows,
        sum(esp_bytes) AS esp_bytes,
        sum(esp_packets) AS esp_packets,
        sum(esp_flows) AS esp_flows,
        sum(icmp_bytes) AS icmp_bytes,
        sum(icmp_packets) AS icmp_packets,
        sum(icmp_flows) AS icmp_flows,
        sum(tcp_fin_bytes) AS tcp_fin_bytes,
        sum(tcp_fin_packets) AS tcp_fin_packets,
        sum(tcp_fin_flows) AS tcp_fin_flows,
        sum(tcp_syn_bytes) AS tcp_syn_bytes,
        sum(tcp_syn_packets) AS tcp_syn_packets,
        sum(tcp_syn_flows) AS tcp_syn_flows,
        sum(tcp_rst_bytes) AS tcp_rst_bytes,
        sum(tcp_rst_packets) AS tcp_rst_packets,
        sum(tcp_rst_flows) AS tcp_rst_flows,
        sum(tcp_psh_bytes) AS tcp_psh_bytes,
        sum(tcp_psh_packets) AS tcp_psh_packets,
        sum(tcp_psh_flows) AS tcp_psh_flows,
        sum(tcp_ack_bytes) AS tcp_ack_bytes,
        sum(tcp_ack_packets) AS tcp_ack_packets,
        sum(tcp_ack_flows) AS tcp_ack_flows,
        sum(tcp_urg_bytes) AS tcp_urg_bytes,
        sum(tcp_urg_packets) AS tcp_urg_packets,
        sum(tcp_urg_flows) AS tcp_urg_flows,
            sum(any_bytes) AS total_bytes
        FROM flows.prefixes_ip_port_1m
        WHERE time_received >= NOW() - INTERVAL 1 HOUR
        GROUP BY prefix, dst_addr, dst_port, time_received
    )
    SELECT * EXCEPT total_bytes
    FROM stats
    QUALIFY total_bytes >= quantile(0.05)(total_bytes) OVER (PARTITION BY prefix, dst_addr);

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_ip_1h_mv
REFRESH EVERY 1 HOUR APPEND TO flows.prefixes_ip_1h AS
    SELECT
        prefix,
        dst_addr,
        toStartOfHour(time_received) AS time_received,
        sum(any_bytes) AS any_bytes,
        sum(any_packets) AS any_packets,
        sum(any_flows) AS any_flows,
        sum(tcp_bytes) AS tcp_bytes,
        sum(tcp_packets) AS tcp_packets,
        sum(tcp_flows) AS tcp_flows,
        sum(udp_bytes) AS udp_bytes,
        sum(udp_packets) AS udp_packets,
        sum(udp_flows) AS udp_flows,
        sum(gre_bytes) AS gre_bytes,
        sum(gre_packets) AS gre_packets,
        sum(gre_flows) AS gre_flows,
        sum(esp_bytes) AS esp_bytes,
        sum(esp_packets) AS esp_packets,
        sum(esp_flows) AS esp_flows,
        sum(icmp_bytes) AS icmp_bytes,
        sum(icmp_packets) AS icmp_packets,
        sum(icmp_flows) AS icmp_flows,
        sum(tcp_fin_bytes) AS tcp_fin_bytes,
        sum(tcp_fin_packets) AS tcp_fin_packets,
        sum(tcp_fin_flows) AS tcp_fin_flows,
        sum(tcp_syn_bytes) AS tcp_syn_bytes,
        sum(tcp_syn_packets) AS tcp_syn_packets,
        sum(tcp_syn_flows) AS tcp_syn_flows,
        sum(tcp_rst_bytes) AS tcp_rst_bytes,
        sum(tcp_rst_packets) AS tcp_rst_packets,
        sum(tcp_rst_flows) AS tcp_rst_flows,
        sum(tcp_psh_bytes) AS tcp_psh_bytes,
        sum(tcp_psh_packets) AS tcp_psh_packets,
        sum(tcp_psh_flows) AS tcp_psh_flows,
        sum(tcp_ack_bytes) AS tcp_ack_bytes,
        sum(tcp_ack_packets) AS tcp_ack_packets,
        sum(tcp_ack_flows) AS tcp_ack_flows,
        sum(tcp_urg_bytes) AS tcp_urg_bytes,
        sum(tcp_urg_packets) AS tcp_urg_packets,
        sum(tcp_urg_flows) AS tcp_urg_flows
    FROM flows.prefixes_ip_1m
    WHERE time_received >= NOW() - INTERVAL 1 HOUR
    GROUP BY prefix, dst_addr, time_received;

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_proto_1h_mv
REFRESH EVERY 1 HOUR APPEND TO flows.prefixes_proto_1h AS
    SELECT
        prefix,
        toStartOfHour(time_received) AS time_received,
        sum(any_bytes) AS any_bytes,
        sum(any_packets) AS any_packets,
        sum(any_flows) AS any_flows,
        sum(tcp_bytes) AS tcp_bytes,
        sum(tcp_packets) AS tcp_packets,
        sum(tcp_flows) AS tcp_flows,
        sum(udp_bytes) AS udp_bytes,
        sum(udp_packets) AS udp_packets,
        sum(udp_flows) AS udp_flows,
        sum(gre_bytes) AS gre_bytes,
        sum(gre_packets) AS gre_packets,
        sum(gre_flows) AS gre_flows,
        sum(esp_bytes) AS esp_bytes,
        sum(esp_packets) AS esp_packets,
        sum(esp_flows) AS esp_flows,
        sum(icmp_bytes) AS icmp_bytes,
        sum(icmp_packets) AS icmp_packets,
        sum(icmp_flows) AS icmp_flows,
        sum(tcp_fin_bytes) AS tcp_fin_bytes,
        sum(tcp_fin_packets) AS tcp_fin_packets,
        sum(tcp_fin_flows) AS tcp_fin_flows,
        sum(tcp_syn_bytes) AS tcp_syn_bytes,
        sum(tcp_syn_packets) AS tcp_syn_packets,
        sum(tcp_syn_flows) AS tcp_syn_flows,
        sum(tcp_rst_bytes) AS tcp_rst_bytes,
        sum(tcp_rst_packets) AS tcp_rst_packets,
        sum(tcp_rst_flows) AS tcp_rst_flows,
        sum(tcp_psh_bytes) AS tcp_psh_bytes,
        sum(tcp_psh_packets) AS tcp_psh_packets,
        sum(tcp_psh_flows) AS tcp_psh_flows,
        sum(tcp_ack_bytes) AS tcp_ack_bytes,
        sum(tcp_ack_packets) AS tcp_ack_packets,
        sum(tcp_ack_flows) AS tcp_ack_flows,
        sum(tcp_urg_bytes) AS tcp_urg_bytes,
        sum(tcp_urg_packets) AS tcp_urg_packets,
        sum(tcp_urg_flows) AS tcp_urg_flows
    FROM flows.prefixes_proto_1m
    WHERE time_received >= NOW() - INTERVAL 1 HOUR
    GROUP BY prefix, time_received;

-- 1d rollups: p95/max of hourly p95 values (from 1h tables)

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_ip_port_1d_mv
REFRESH EVERY 1 DAY APPEND TO flows.prefixes_ip_port_1d AS
    WITH stats AS (
        SELECT
            prefix,
            dst_addr,
            dst_port,
            toStartOfDay(time_received) AS time_received,
        quantile(0.95)(any_bytes) AS any_p95_bytes,
        quantile(0.95)(any_packets) AS any_p95_packets,
        quantile(0.95)(any_flows) AS any_p95_flows,
        max(any_bytes) AS any_max_bytes,
        max(any_packets) AS any_max_packets,
        max(any_flows) AS any_max_flows,
        quantile(0.95)(tcp_bytes) AS tcp_p95_bytes,
        quantile(0.95)(tcp_packets) AS tcp_p95_packets,
        quantile(0.95)(tcp_flows) AS tcp_p95_flows,
        max(tcp_bytes) AS tcp_max_bytes,
        max(tcp_packets) AS tcp_max_packets,
        max(tcp_flows) AS tcp_max_flows,
        quantile(0.95)(udp_bytes) AS udp_p95_bytes,
        quantile(0.95)(udp_packets) AS udp_p95_packets,
        quantile(0.95)(udp_flows) AS udp_p95_flows,
        max(udp_bytes) AS udp_max_bytes,
        max(udp_packets) AS udp_max_packets,
        max(udp_flows) AS udp_max_flows,
        quantile(0.95)(gre_bytes) AS gre_p95_bytes,
        quantile(0.95)(gre_packets) AS gre_p95_packets,
        quantile(0.95)(gre_flows) AS gre_p95_flows,
        max(gre_bytes) AS gre_max_bytes,
        max(gre_packets) AS gre_max_packets,
        max(gre_flows) AS gre_max_flows,
        quantile(0.95)(esp_bytes) AS esp_p95_bytes,
        quantile(0.95)(esp_packets) AS esp_p95_packets,
        quantile(0.95)(esp_flows) AS esp_p95_flows,
        max(esp_bytes) AS esp_max_bytes,
        max(esp_packets) AS esp_max_packets,
        max(esp_flows) AS esp_max_flows,
        quantile(0.95)(icmp_bytes) AS icmp_p95_bytes,
        quantile(0.95)(icmp_packets) AS icmp_p95_packets,
        quantile(0.95)(icmp_flows) AS icmp_p95_flows,
        max(icmp_bytes) AS icmp_max_bytes,
        max(icmp_packets) AS icmp_max_packets,
        max(icmp_flows) AS icmp_max_flows,
        quantile(0.95)(tcp_fin_bytes) AS tcp_fin_p95_bytes,
        quantile(0.95)(tcp_fin_packets) AS tcp_fin_p95_packets,
        quantile(0.95)(tcp_fin_flows) AS tcp_fin_p95_flows,
        max(tcp_fin_bytes) AS tcp_fin_max_bytes,
        max(tcp_fin_packets) AS tcp_fin_max_packets,
        max(tcp_fin_flows) AS tcp_fin_max_flows,
        quantile(0.95)(tcp_syn_bytes) AS tcp_syn_p95_bytes,
        quantile(0.95)(tcp_syn_packets) AS tcp_syn_p95_packets,
        quantile(0.95)(tcp_syn_flows) AS tcp_syn_p95_flows,
        max(tcp_syn_bytes) AS tcp_syn_max_bytes,
        max(tcp_syn_packets) AS tcp_syn_max_packets,
        max(tcp_syn_flows) AS tcp_syn_max_flows,
        quantile(0.95)(tcp_rst_bytes) AS tcp_rst_p95_bytes,
        quantile(0.95)(tcp_rst_packets) AS tcp_rst_p95_packets,
        quantile(0.95)(tcp_rst_flows) AS tcp_rst_p95_flows,
        max(tcp_rst_bytes) AS tcp_rst_max_bytes,
        max(tcp_rst_packets) AS tcp_rst_max_packets,
        max(tcp_rst_flows) AS tcp_rst_max_flows,
        quantile(0.95)(tcp_psh_bytes) AS tcp_psh_p95_bytes,
        quantile(0.95)(tcp_psh_packets) AS tcp_psh_p95_packets,
        quantile(0.95)(tcp_psh_flows) AS tcp_psh_p95_flows,
        max(tcp_psh_bytes) AS tcp_psh_max_bytes,
        max(tcp_psh_packets) AS tcp_psh_max_packets,
        max(tcp_psh_flows) AS tcp_psh_max_flows,
        quantile(0.95)(tcp_ack_bytes) AS tcp_ack_p95_bytes,
        quantile(0.95)(tcp_ack_packets) AS tcp_ack_p95_packets,
        quantile(0.95)(tcp_ack_flows) AS tcp_ack_p95_flows,
        max(tcp_ack_bytes) AS tcp_ack_max_bytes,
        max(tcp_ack_packets) AS tcp_ack_max_packets,
        max(tcp_ack_flows) AS tcp_ack_max_flows,
        quantile(0.95)(tcp_urg_bytes) AS tcp_urg_p95_bytes,
        quantile(0.95)(tcp_urg_packets) AS tcp_urg_p95_packets,
        quantile(0.95)(tcp_urg_flows) AS tcp_urg_p95_flows,
        max(tcp_urg_bytes) AS tcp_urg_max_bytes,
        max(tcp_urg_packets) AS tcp_urg_max_packets,
        max(tcp_urg_flows) AS tcp_urg_max_flows,
            sum(any_bytes) AS total_bytes
        FROM flows.prefixes_ip_port_1h
        WHERE time_received >= NOW() - INTERVAL 1 DAY
        GROUP BY prefix, dst_addr, dst_port, time_received
    )
    SELECT * EXCEPT total_bytes
    FROM stats
    QUALIFY total_bytes >= quantile(0.05)(total_bytes) OVER (PARTITION BY prefix, dst_addr);

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_proto_1d_mv
REFRESH EVERY 1 DAY APPEND TO flows.prefixes_proto_1d AS
    SELECT
        prefix,
        toStartOfDay(time_received) AS time_received,
        quantile(0.95)(any_bytes) AS any_p95_bytes,
        quantile(0.95)(any_packets) AS any_p95_packets,
        quantile(0.95)(any_flows) AS any_p95_flows,
        max(any_bytes) AS any_max_bytes,
        max(any_packets) AS any_max_packets,
        max(any_flows) AS any_max_flows,
        quantile(0.95)(tcp_bytes) AS tcp_p95_bytes,
        quantile(0.95)(tcp_packets) AS tcp_p95_packets,
        quantile(0.95)(tcp_flows) AS tcp_p95_flows,
        max(tcp_bytes) AS tcp_max_bytes,
        max(tcp_packets) AS tcp_max_packets,
        max(tcp_flows) AS tcp_max_flows,
        quantile(0.95)(udp_bytes) AS udp_p95_bytes,
        quantile(0.95)(udp_packets) AS udp_p95_packets,
        quantile(0.95)(udp_flows) AS udp_p95_flows,
        max(udp_bytes) AS udp_max_bytes,
        max(udp_packets) AS udp_max_packets,
        max(udp_flows) AS udp_max_flows,
        quantile(0.95)(gre_bytes) AS gre_p95_bytes,
        quantile(0.95)(gre_packets) AS gre_p95_packets,
        quantile(0.95)(gre_flows) AS gre_p95_flows,
        max(gre_bytes) AS gre_max_bytes,
        max(gre_packets) AS gre_max_packets,
        max(gre_flows) AS gre_max_flows,
        quantile(0.95)(esp_bytes) AS esp_p95_bytes,
        quantile(0.95)(esp_packets) AS esp_p95_packets,
        quantile(0.95)(esp_flows) AS esp_p95_flows,
        max(esp_bytes) AS esp_max_bytes,
        max(esp_packets) AS esp_max_packets,
        max(esp_flows) AS esp_max_flows,
        quantile(0.95)(icmp_bytes) AS icmp_p95_bytes,
        quantile(0.95)(icmp_packets) AS icmp_p95_packets,
        quantile(0.95)(icmp_flows) AS icmp_p95_flows,
        max(icmp_bytes) AS icmp_max_bytes,
        max(icmp_packets) AS icmp_max_packets,
        max(icmp_flows) AS icmp_max_flows,
        quantile(0.95)(tcp_fin_bytes) AS tcp_fin_p95_bytes,
        quantile(0.95)(tcp_fin_packets) AS tcp_fin_p95_packets,
        quantile(0.95)(tcp_fin_flows) AS tcp_fin_p95_flows,
        max(tcp_fin_bytes) AS tcp_fin_max_bytes,
        max(tcp_fin_packets) AS tcp_fin_max_packets,
        max(tcp_fin_flows) AS tcp_fin_max_flows,
        quantile(0.95)(tcp_syn_bytes) AS tcp_syn_p95_bytes,
        quantile(0.95)(tcp_syn_packets) AS tcp_syn_p95_packets,
        quantile(0.95)(tcp_syn_flows) AS tcp_syn_p95_flows,
        max(tcp_syn_bytes) AS tcp_syn_max_bytes,
        max(tcp_syn_packets) AS tcp_syn_max_packets,
        max(tcp_syn_flows) AS tcp_syn_max_flows,
        quantile(0.95)(tcp_rst_bytes) AS tcp_rst_p95_bytes,
        quantile(0.95)(tcp_rst_packets) AS tcp_rst_p95_packets,
        quantile(0.95)(tcp_rst_flows) AS tcp_rst_p95_flows,
        max(tcp_rst_bytes) AS tcp_rst_max_bytes,
        max(tcp_rst_packets) AS tcp_rst_max_packets,
        max(tcp_rst_flows) AS tcp_rst_max_flows,
        quantile(0.95)(tcp_psh_bytes) AS tcp_psh_p95_bytes,
        quantile(0.95)(tcp_psh_packets) AS tcp_psh_p95_packets,
        quantile(0.95)(tcp_psh_flows) AS tcp_psh_p95_flows,
        max(tcp_psh_bytes) AS tcp_psh_max_bytes,
        max(tcp_psh_packets) AS tcp_psh_max_packets,
        max(tcp_psh_flows) AS tcp_psh_max_flows,
        quantile(0.95)(tcp_ack_bytes) AS tcp_ack_p95_bytes,
        quantile(0.95)(tcp_ack_packets) AS tcp_ack_p95_packets,
        quantile(0.95)(tcp_ack_flows) AS tcp_ack_p95_flows,
        max(tcp_ack_bytes) AS tcp_ack_max_bytes,
        max(tcp_ack_packets) AS tcp_ack_max_packets,
        max(tcp_ack_flows) AS tcp_ack_max_flows,
        quantile(0.95)(tcp_urg_bytes) AS tcp_urg_p95_bytes,
        quantile(0.95)(tcp_urg_packets) AS tcp_urg_p95_packets,
        quantile(0.95)(tcp_urg_flows) AS tcp_urg_p95_flows,
        max(tcp_urg_bytes) AS tcp_urg_max_bytes,
        max(tcp_urg_packets) AS tcp_urg_max_packets,
        max(tcp_urg_flows) AS tcp_urg_max_flows
    FROM flows.prefixes_proto_1h
    WHERE time_received >= NOW() - INTERVAL 1 DAY
    GROUP BY prefix, time_received;

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.prefixes_ip_1d_mv
REFRESH EVERY 1 DAY APPEND TO flows.prefixes_ip_1d AS
    SELECT
        prefix,
        dst_addr,
        toStartOfDay(time_received) AS time_received,
        quantile(0.95)(any_bytes) AS any_p95_bytes,
        quantile(0.95)(any_packets) AS any_p95_packets,
        quantile(0.95)(any_flows) AS any_p95_flows,
        max(any_bytes) AS any_max_bytes,
        max(any_packets) AS any_max_packets,
        max(any_flows) AS any_max_flows,
        quantile(0.95)(tcp_bytes) AS tcp_p95_bytes,
        quantile(0.95)(tcp_packets) AS tcp_p95_packets,
        quantile(0.95)(tcp_flows) AS tcp_p95_flows,
        max(tcp_bytes) AS tcp_max_bytes,
        max(tcp_packets) AS tcp_max_packets,
        max(tcp_flows) AS tcp_max_flows,
        quantile(0.95)(udp_bytes) AS udp_p95_bytes,
        quantile(0.95)(udp_packets) AS udp_p95_packets,
        quantile(0.95)(udp_flows) AS udp_p95_flows,
        max(udp_bytes) AS udp_max_bytes,
        max(udp_packets) AS udp_max_packets,
        max(udp_flows) AS udp_max_flows,
        quantile(0.95)(gre_bytes) AS gre_p95_bytes,
        quantile(0.95)(gre_packets) AS gre_p95_packets,
        quantile(0.95)(gre_flows) AS gre_p95_flows,
        max(gre_bytes) AS gre_max_bytes,
        max(gre_packets) AS gre_max_packets,
        max(gre_flows) AS gre_max_flows,
        quantile(0.95)(esp_bytes) AS esp_p95_bytes,
        quantile(0.95)(esp_packets) AS esp_p95_packets,
        quantile(0.95)(esp_flows) AS esp_p95_flows,
        max(esp_bytes) AS esp_max_bytes,
        max(esp_packets) AS esp_max_packets,
        max(esp_flows) AS esp_max_flows,
        quantile(0.95)(icmp_bytes) AS icmp_p95_bytes,
        quantile(0.95)(icmp_packets) AS icmp_p95_packets,
        quantile(0.95)(icmp_flows) AS icmp_p95_flows,
        max(icmp_bytes) AS icmp_max_bytes,
        max(icmp_packets) AS icmp_max_packets,
        max(icmp_flows) AS icmp_max_flows,
        quantile(0.95)(tcp_fin_bytes) AS tcp_fin_p95_bytes,
        quantile(0.95)(tcp_fin_packets) AS tcp_fin_p95_packets,
        quantile(0.95)(tcp_fin_flows) AS tcp_fin_p95_flows,
        max(tcp_fin_bytes) AS tcp_fin_max_bytes,
        max(tcp_fin_packets) AS tcp_fin_max_packets,
        max(tcp_fin_flows) AS tcp_fin_max_flows,
        quantile(0.95)(tcp_syn_bytes) AS tcp_syn_p95_bytes,
        quantile(0.95)(tcp_syn_packets) AS tcp_syn_p95_packets,
        quantile(0.95)(tcp_syn_flows) AS tcp_syn_p95_flows,
        max(tcp_syn_bytes) AS tcp_syn_max_bytes,
        max(tcp_syn_packets) AS tcp_syn_max_packets,
        max(tcp_syn_flows) AS tcp_syn_max_flows,
        quantile(0.95)(tcp_rst_bytes) AS tcp_rst_p95_bytes,
        quantile(0.95)(tcp_rst_packets) AS tcp_rst_p95_packets,
        quantile(0.95)(tcp_rst_flows) AS tcp_rst_p95_flows,
        max(tcp_rst_bytes) AS tcp_rst_max_bytes,
        max(tcp_rst_packets) AS tcp_rst_max_packets,
        max(tcp_rst_flows) AS tcp_rst_max_flows,
        quantile(0.95)(tcp_psh_bytes) AS tcp_psh_p95_bytes,
        quantile(0.95)(tcp_psh_packets) AS tcp_psh_p95_packets,
        quantile(0.95)(tcp_psh_flows) AS tcp_psh_p95_flows,
        max(tcp_psh_bytes) AS tcp_psh_max_bytes,
        max(tcp_psh_packets) AS tcp_psh_max_packets,
        max(tcp_psh_flows) AS tcp_psh_max_flows,
        quantile(0.95)(tcp_ack_bytes) AS tcp_ack_p95_bytes,
        quantile(0.95)(tcp_ack_packets) AS tcp_ack_p95_packets,
        quantile(0.95)(tcp_ack_flows) AS tcp_ack_p95_flows,
        max(tcp_ack_bytes) AS tcp_ack_max_bytes,
        max(tcp_ack_packets) AS tcp_ack_max_packets,
        max(tcp_ack_flows) AS tcp_ack_max_flows,
        quantile(0.95)(tcp_urg_bytes) AS tcp_urg_p95_bytes,
        quantile(0.95)(tcp_urg_packets) AS tcp_urg_p95_packets,
        quantile(0.95)(tcp_urg_flows) AS tcp_urg_p95_flows,
        max(tcp_urg_bytes) AS tcp_urg_max_bytes,
        max(tcp_urg_packets) AS tcp_urg_max_packets,
        max(tcp_urg_flows) AS tcp_urg_max_flows
    FROM flows.prefixes_ip_1h
    WHERE time_received >= NOW() - INTERVAL 1 DAY
    GROUP BY prefix, dst_addr, time_received;

CREATE MATERIALIZED VIEW IF NOT EXISTS flows.expression_metrics_1m_mv TO flows.expression_metrics_1m AS
SELECT 
    expression_id, 
    toStartOfMinute(time_received) AS time_received, 
    sum(bytes) AS bytes, 
    sum(packets) AS packets
FROM flows.expression_metrics_1m 
GROUP BY 
    expression_id, 
    time_received;
